packages:
  - '.'

allowBuilds:
  msw: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  "@types/react": "19.3.0"
  "@types/react-dom": "19.3.0"
  "zod@4.4.3": "4.1.13"
